---
apiVersion: v1
kind: Secret
metadata:
  name: pipelines-as-code-secret-${component_name}
  labels:
    originating-tool: "${originating_tool}"
type: Opaque
stringData:
  password: ${GITHUB_TOKEN}
