---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-to-cspv2
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task that creates an InternalRequest to check connectivity
    to CSPv2 (Unified Downloads).
  params:
    - name: pipelineRunUid
      type: string
      description: The uid of the current pipelineRun. Used as a label value when creating internal requests
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the release-service-catalog tasks and stepactions to be used are stored
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
    - name: requestTimeout
      type: string
      default: "1800"
      description: InternalRequest timeout
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  results:
    - name: pushResult
      description: Result of the operation (pass/fail)
  volumes:
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    securityContext:
      runAsUser: 1001
    volumeMounts:
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
  steps:
    - name: run-internal-request
      image: quay.io/konflux-ci/release-service-utils@sha256:17925cd6c631c3828966457099f117c894eb01983b8639920bf82b1a5e1841d0
      computeResources:
        limits:
          memory: 512Mi
        requests:
          memory: 512Mi
          cpu: 50m
      script: |
        #!/usr/bin/env bash
        set -eo pipefail

        TASK_LABEL="internal-services.appstudio.openshift.io/group-id"
        TASK_ID=$(context.taskRun.uid)
        PIPELINERUN_LABEL="internal-services.appstudio.openshift.io/pipelinerun-uid"

        IR_RESULT_FILE=$(mktemp)
        trap 'rm -f "${IR_RESULT_FILE}"' EXIT

        internal-request --pipeline "push-to-cspv2" \
            -p taskGitUrl="$(params.taskGitUrl)" \
            -p taskGitRevision="$(params.taskGitRevision)" \
            -l ${TASK_LABEL}="${TASK_ID}" \
            -l ${PIPELINERUN_LABEL}="$(params.pipelineRunUid)" \
            -t "$(params.requestTimeout)" \
            --pipeline-timeout 0h30m0s \
            --task-timeout 0h20m0s \
            --finally-timeout 0h10m0s \
            -s true \
            | tee "${IR_RESULT_FILE}" || \
            (grep "^\[" "${IR_RESULT_FILE}" | jq . && exit 1)

        internalRequest=$(awk -F"'" '/created/ { print $2 }' "${IR_RESULT_FILE}")
        echo "done (${internalRequest})"

        results=$(kubectl get internalrequest "${internalRequest}" -o=jsonpath='{.status.results}')
        pushResult=$(echo "${results}" | jq -r '.result')
        echo "Push result: ${pushResult}"
        echo -n "${pushResult}" > "$(results.pushResult.path)"
